export const BASE = "https://www.tiktok.com";
export const API = "https://www.tiktok.com/api";

export const ENDPOINTS = {
  trending: `${API}/recommend/itemlist/`,
  hashtag_info: `${API}/challenge/detail/`,
  hashtag_feed: `${API}/challenge/item_list/`,
  user_info: `${API}/user/detail/`,
  user_feed: `${API}/post/item_list/`,
  search_general: `${API}/search/general/full/`,
  video_detail: `${API}/item/detail/`,
  comment_list: `${API}/comment/list/`,
  like_video: `${API}/commit/item/digg/`,
  save_video: `${API}/commit/item/collect/`,
  feed_foryou: `${API}/recommend/itemlist/`,
  feed_following: `${API}/follow/item_list/`,
  whoami: `${API}/user/detail/`,
  comment_post: `${API}/commit/comment/publish/`,
  follow_user: `${API}/commit/follow/user/`,
  unfollow_user: `${API}/commit/follow/user/`,
  following_list: `${API}/follow/list/`,
  follower_list: `${API}/follower/list/`,
  video_delete: `${API}/commit/video/delete/`,
} as const;

// Common query params required by TikTok API
export const BASE_PARAMS: Record<string, string> = {
  aid: "1988",
  app_language: "en",
  app_name: "tiktok_web",
  browser_language: "en-US",
  browser_name: "Mozilla",
  browser_online: "true",
  browser_platform: "MacIntel",
  browser_version: "5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
  channel: "tiktok_web",
  cookie_enabled: "true",
  device_platform: "web_pc",
  focus_state: "true",
  from_page: "fyp",
  history_len: "3",
  is_fullscreen: "false",
  is_page_visible: "true",
  language: "en",
  os: "mac",
  priority_region: "",
  referer: "",
  region: "US",
  screen_height: "900",
  screen_width: "1440",
  webcast_language: "en",
};
